---
- hosts: slave2
  name: Install
  become: yes
  tasks:
          - name: Install Apache2 on  Ubuntu server
            apt:
                    name: apache2
                    state: present
                    update_cache: yes
            notify:
                    - Restart apache2

  handlers:
          - name: Restart apache2
            service:
                    name:  apache2
                    state: restarted
